services:
  - type: web
    name: covid-chatserver-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: covid-chatserver-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatmain.py conf.json